#!/usr/bin/env python3
"""Generate the compiler's opcode table from SpiderMonkey's vm/Opcodes.h.

The compiler's `JSOp` enum, with each opcode's length and stack effect, is
generated from the engine's `FOR_EACH_OPCODE` table and checked in under
compiler/src/opcodes/<version>.rs, one file per supported engine version; a
cargo feature of the same name selects the version a build targets. The
generated file records a digest of the whole Opcodes.h it came from, so the
`check` command below detects any change to the header, including a change
to what an opcode means that leaves the table's shape alone.

    scripts/gen_opcodes.py generate <version> <path/to/Opcodes.h>
        Write compiler/src/opcodes/<version>.rs.

    scripts/gen_opcodes.py check <version> <path/to/Opcodes.h>
        Exit non-zero, with a diff, if compiler/src/opcodes/<version>.rs
        is not what the given Opcodes.h generates. Builds against an engine
        run this for the version they select.

Adding an engine version: generate its file, add the feature to
compiler/Cargo.toml (and the forwarding features of the crates that depend
on it), add the arm to compiler/src/opcodes/mod.rs, and gate whatever the
lowerings need to do differently on `feature = "<version>"`.
"""

import argparse
import difflib
import hashlib
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
OPCODES_DIR = REPO / "compiler" / "src" / "opcodes"

VERSION_RE = re.compile(r"^[a-z][a-z0-9_]*$")
IDENT_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


class Opcode:
    def __init__(self, name, length, nuses, ndefs):
        self.name = name
        self.length = length
        self.nuses = nuses
        self.ndefs = ndefs


def parse_opcodes(text):
    """The opcodes of the FOR_EACH_OPCODE table, in numbering order.

    Each entry is `MACRO(op, op_snake, token, length, nuses, ndefs, format)`;
    a negative nuses means the count is variable.
    """
    ops = []
    in_table = False
    for line in text.splitlines():
        if not in_table:
            if "#define FOR_EACH_OPCODE" in line:
                in_table = True
        elif "FOR_EACH_TRAILING_UNUSED_OPCODE" in line:
            break
        else:
            start = line.find("MACRO(")
            if start < 0:
                continue
            end = line.find(")", start)
            if end < 0:
                raise SystemExit(f"unterminated MACRO( entry: {line.strip()}")
            fields = [f.strip() for f in line[start + len("MACRO("):end].split(",")]
            if len(fields) < 7:
                raise SystemExit(f"malformed opcode entry: {line.strip()}")
            name = fields[0]
            if not IDENT_RE.match(name):
                raise SystemExit(f"malformed opcode name: {line.strip()}")
            ops.append(Opcode(name, int(fields[3]), int(fields[4]), int(fields[5])))
    if not in_table:
        raise SystemExit("no FOR_EACH_OPCODE table found")
    if len(ops) > 256:
        raise SystemExit(f"{len(ops)} opcodes do not fit an opcode byte")
    return ops


def render(version, text, ops):
    digest = hashlib.sha256(text.encode("utf-8")).hexdigest()
    out = []
    w = out.append
    w("// Generated by scripts/gen_opcodes.py from SpiderMonkey's vm/Opcodes.h.")
    w("// Do not edit; regenerate with")
    w(f"//   scripts/gen_opcodes.py generate {version} <path/to/Opcodes.h>")
    w("")
    w("/// The engine version this table was generated for.")
    w(f'pub const ENGINE_VERSION: &str = "{version}";')
    w("/// SHA-256 of the Opcodes.h this table was generated from.")
    w(f'pub const OPCODES_H_SHA256: &str = "{digest}";')
    w("")
    w("#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]")
    w("#[repr(u16)]")
    w("pub enum JSOp {")
    for op in ops:
        w(f"    {op.name},")
    w("}")
    w("#[allow(clippy::len_without_is_empty)]")
    w("impl JSOp {")
    w("    pub fn from_byte(value: u8) -> Option<JSOp> {")
    w("        match value {")
    for i, op in enumerate(ops):
        w(f"            {i} => Some(JSOp::{op.name}),")
    for i in range(len(ops), 256):
        w(f"            {i} => None,")
    w("        }")
    w("    }")
    w("    pub fn len(&self) -> u32 {")
    w("        match self {")
    for op in ops:
        w(f"            JSOp::{op.name} => {op.length},")
    w("        }")
    w("    }")
    w("    pub fn nuses(&self) -> Option<u32> {")
    w("        match self {")
    for op in ops:
        if op.nuses < 0:
            w(f"            JSOp::{op.name} => None,")
        else:
            w(f"            JSOp::{op.name} => Some({op.nuses}),")
    w("        }")
    w("    }")
    w("    pub fn ndefs(&self) -> u32 {")
    w("        match self {")
    for op in ops:
        w(f"            JSOp::{op.name} => {op.ndefs},")
    w("        }")
    w("    }")
    w("}")
    return "\n".join(out) + "\n"


def known_versions():
    return sorted(p.stem for p in OPCODES_DIR.glob("*.rs") if p.stem != "mod")


def main():
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    sub = parser.add_subparsers(dest="command", required=True)
    for name, help_text in (
        ("generate", "write compiler/src/opcodes/<version>.rs"),
        ("check", "verify compiler/src/opcodes/<version>.rs against an Opcodes.h"),
    ):
        p = sub.add_parser(name, help=help_text)
        p.add_argument("version", help="engine version name, e.g. ff147")
        p.add_argument("opcodes_h", type=Path, help="path to the engine's vm/Opcodes.h")
    args = parser.parse_args()

    if not VERSION_RE.match(args.version):
        raise SystemExit(f"invalid version name {args.version!r}: use e.g. ff147")
    try:
        text = args.opcodes_h.read_text(encoding="utf-8")
    except OSError as e:
        raise SystemExit(f"reading {args.opcodes_h}: {e}")
    generated = render(args.version, text, parse_opcodes(text))
    target = OPCODES_DIR / f"{args.version}.rs"

    if args.command == "generate":
        OPCODES_DIR.mkdir(parents=True, exist_ok=True)
        target.write_text(generated, encoding="utf-8")
        print(f"wrote {target.relative_to(REPO)}")
        return 0

    if not target.exists():
        raise SystemExit(
            f"no opcode table for engine version {args.version!r} "
            f"({target.relative_to(REPO)}); known versions: {', '.join(known_versions()) or 'none'}"
        )
    current = target.read_text(encoding="utf-8")
    if current == generated:
        print(f"{target.relative_to(REPO)} matches {args.opcodes_h}")
        return 0
    diff = difflib.unified_diff(
        current.splitlines(keepends=True),
        generated.splitlines(keepends=True),
        fromfile=str(target.relative_to(REPO)),
        tofile=f"generated from {args.opcodes_h}",
    )
    sys.stdout.writelines(diff)
    print(
        f"\nerror: {target.relative_to(REPO)} is not what {args.opcodes_h} generates.\n"
        f"The engine's Opcodes.h changed. Review the lowerings (compiler/src/opsem.rs and\n"
        f"compiler/src/wasm/) against the change, then regenerate the table for this\n"
        f"version, or generate a new version:\n"
        f"  scripts/gen_opcodes.py generate {args.version} {args.opcodes_h}",
        file=sys.stderr,
    )
    return 1


if __name__ == "__main__":
    sys.exit(main())
